version: 2.1

jobs:
  print_env_var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "print env var"
          command: |
            echo $MY_NAME
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      #- checkout
      - run:
          name: "save file" 
          command: |
            echo "My name is Juanito" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      #- checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "read file" 
          command: |
            cat ~/output.txt
          

workflows:
  own-tests-of-capabilities:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output