version: 2.1

jobs:
  print_env_var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "print env var"
          command: |
            echo $MY_NAME

workflows:
  my-first-test:
    jobs:
      - print_env_var